### PR TITLE
Fix/separate data

### LINKED ISSUE #54: code reorg: separate data
Put all data subdirs into a data/ directory, and all source code into a src/ to make it very obvious which parts of this repo are code vs data.

### PR DESCRIPTION
**Pull request by rugeli**
Problem
=======
What is the problem this work solves, including
closes #54 

Solution
========
What I/we did to solve this problem

- created directories `data`, `bin`, `src` to separate data and code in the repo 
- changed file paths in `Makefile`, `gitignore`, `process_dataset` and other files accordingly 

with @meganrm 

## Type of change
Please delete options that are not relevant.

* Maintenance and code clean-up

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -3,8 +3,8 @@
 node_modules
 */node_modules
 .env
-data/**/cell-feature-analysis.json
-data/**/file-info.json
+tmp/**/cell-feature-analysis.json
+tmp/**/file-info.json
```
Comment (toloudis) [inline .gitignore:7]: could just gitignore `tmp`

File: bin/check-input-datasets.js [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+      `${fileName}: check against ${schemaFileName}`,
+      "\x1b[32m",
+      "passed",
+      "\x1b[0m"
+    );
+    return false;
+  }
+};
+
+const unpackInputDataset = async (datasetReadFolder) => {
```
Comment (toloudis) [inline bin/check-input-datasets.js:74]: this function is a good candidate to move into `src/process-single-dataset` or utils.  for `bin` scripts it would be good to move implementation details out to `src` as much as it makes sense to.

File: bin/check-input-datasets.js [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+  inputDataSet,
+];
+const INPUT_DATASET_SCHEMA_FILE = "input-dataset.schema.json";
+const INPUT_MEGASET_SCHEMA_FILE = "input-megaset.schema.json";
+
+const ajv = new Ajv({
+  coerceTypes: true,
+  removeAdditional: true,
+  schemas: INPUT_DATASET_SCHEMA,
+});
```
Comment (toloudis) [inline bin/check-input-datasets.js:46]: most of lines 12-46 could be refactored into src/ as a single function with a name like getInputDatasetSchema

File: package.json [hunk 4]
```diff
@@ -11,13 +11,13 @@
...
   "scripts": {
     "test": "jest --env node --forceExit",
-    "process-dataset": "node process-dataset",
-    "upload-image": "node upload-dataset-image",
-    "release-dataset": "node release-dataset",
-    "prepublish-docs": "cd ./data-validation && make docs",
+    "process-dataset": "node bin/process-dataset",
+    "upload-image": "node bin/upload-dataset-image",
+    "release-dataset": "node bin/release-dataset",
+    "prepublish-docs": "cd bin && make docs",
```
Comment (toloudis) [inline package.json:17]: just wondering, why is Makefile in `bin/` ?  Isn't Makefile a package meta thing that should live down here next to package.json?

Comment (meganrm) [reply package.json:17]: yeah, that was my decision, I wasn't sure where to put it, but yeah we can put it up a level

File: bin/check-input-datasets.js (hunk 2 above)
Comment (rugeli) [reply bin/check-input-datasets.js]: Sure I moved it to `src/process-single-dataset/steps` as a single function

Comment (meganrm) [reply bin/check-input-datasets.js]: it should be moved to data validation. `Steps` is specifically for the steps outlined in `process-datasets/index.js`

**Review by meganrm — APPROVED** [review]

File: Makefile [hunk 5]
```diff
@@ -1,18 +1,17 @@
...
 DATABASE_SPEC = DatabaseSpecification
-HTML_DOCS = ../dist/$(DATABASE_SPEC).html ../dist/${HANDOFF_SPEC}.html
-TARGETS = ../docs/$(DATABASE_SPEC).adoc ../docs/${HANDOFF_SPEC}.adoc
+HTML_DOCS = ./dist/$(DATABASE_SPEC).html ./dist/${HANDOFF_SPEC}.html
+TARGETS = ./docs/$(DATABASE_SPEC).adoc ./docs/${HANDOFF_SPEC}.adoc
 # all: $(TARGETS)
+WETZEL = ./wetzel/bin/wetzel.js
 
-WETZEL = ../wetzel/bin/wetzel.js
+SCHEMALINK = ../src/data-validation/schema
```
Comment (toloudis) [inline Makefile:8]: should this be single dot instead of double dot?

**Review by toloudis — APPROVED** [review]
This is looking great!   I saw one little thing to check in the Makefile.

File: Makefile (hunk 5 above)
Comment (rugeli) [reply Makefile:8]: Thanks for bringing it up, I've been experimenting with the dots quite a bit, and I found that a single dot in SCHEMALINK didn't work but using a double dot did

Comment (toloudis) [reply Makefile:8]: Anyone seeing it might be suspicious, but I guess the program that is looking for it has a current working directory one level deeper.
